/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PlayerScreenRouteImport } from './routes/player-screen'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PareamentoRouteImport } from './routes/pareamento'
import { Route as PairRouteImport } from './routes/pair'
import { Route as PagamentosRouteImport } from './routes/pagamentos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LicencasRouteImport } from './routes/licencas'
import { Route as FaturasRouteImport } from './routes/faturas'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfigurarRouteImport } from './routes/configurar'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AssinaturasRouteImport } from './routes/assinaturas'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminSaasRouteImport } from './routes/admin-saas'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminSaasIndexRouteImport } from './routes/admin-saas.index'
import { Route as PlayerWebRouteImport } from './routes/player.web'
import { Route as PlayerScreenIdRouteImport } from './routes/player.$screenId'
import { Route as DisplayTokenRouteImport } from './routes/display.$token'
import { Route as AppVisualizacaoRouteImport } from './routes/app.visualizacao'
import { Route as AppUsuariosRouteImport } from './routes/app.usuarios'
import { Route as AppUnidadesRouteImport } from './routes/app.unidades'
import { Route as AppTelasRouteImport } from './routes/app.telas'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppPreviewRouteImport } from './routes/app.preview'
import { Route as AppPlaylistsRouteImport } from './routes/app.playlists'
import { Route as AppOperadorRouteImport } from './routes/app.operador'
import { Route as AppMonitoramentoRouteImport } from './routes/app.monitoramento'
import { Route as AppMidiasRouteImport } from './routes/app.midias'
import { Route as AppGruposRouteImport } from './routes/app.grupos'
import { Route as AppFaturasRouteImport } from './routes/app.faturas'
import { Route as AppEmpresasRouteImport } from './routes/app.empresas'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppCampanhasRouteImport } from './routes/app.campanhas'
import { Route as AppAuditoriaRouteImport } from './routes/app.auditoria'
import { Route as AppAssinaturaRouteImport } from './routes/app.assinatura'
import { Route as AppAlertasRouteImport } from './routes/app.alertas'
import { Route as AppAgendamentosRouteImport } from './routes/app.agendamentos'
import { Route as AdminSaasPlanosRouteImport } from './routes/admin-saas.planos'
import { Route as AdminSaasPagamentosRouteImport } from './routes/admin-saas.pagamentos'
import { Route as AdminSaasLogsRouteImport } from './routes/admin-saas.logs'
import { Route as AdminSaasLicencasRouteImport } from './routes/admin-saas.licencas'
import { Route as AdminSaasDiagnosticoRouteImport } from './routes/admin-saas.diagnostico'
import { Route as AdminSaasClientesRouteImport } from './routes/admin-saas.clientes'
import { Route as AdminSaasAssinaturasRouteImport } from './routes/admin-saas.assinaturas'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerScreenRoute = PlayerScreenRouteImport.update({
  id: '/player-screen',
  path: '/player-screen',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PareamentoRoute = PareamentoRouteImport.update({
  id: '/pareamento',
  path: '/pareamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosRoute = PagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LicencasRoute = LicencasRouteImport.update({
  id: '/licencas',
  path: '/licencas',
  getParentRoute: () => rootRouteImport,
} as any)
const FaturasRoute = FaturasRouteImport.update({
  id: '/faturas',
  path: '/faturas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurarRoute = ConfigurarRouteImport.update({
  id: '/configurar',
  path: '/configurar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturasRoute = AssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSaasRoute = AdminSaasRouteImport.update({
  id: '/admin-saas',
  path: '/admin-saas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminSaasIndexRoute = AdminSaasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSaasRoute,
} as any)
const PlayerWebRoute = PlayerWebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerScreenIdRoute = PlayerScreenIdRouteImport.update({
  id: '/$screenId',
  path: '/$screenId',
  getParentRoute: () => PlayerRoute,
} as any)
const DisplayTokenRoute = DisplayTokenRouteImport.update({
  id: '/display/$token',
  path: '/display/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVisualizacaoRoute = AppVisualizacaoRouteImport.update({
  id: '/visualizacao',
  path: '/visualizacao',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppUnidadesRoute = AppUnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => AppRoute,
} as any)
const AppTelasRoute = AppTelasRouteImport.update({
  id: '/telas',
  path: '/telas',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPreviewRoute = AppPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaylistsRoute = AppPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => AppRoute,
} as any)
const AppOperadorRoute = AppOperadorRouteImport.update({
  id: '/operador',
  path: '/operador',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoramentoRoute = AppMonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => AppRoute,
} as any)
const AppMidiasRoute = AppMidiasRouteImport.update({
  id: '/midias',
  path: '/midias',
  getParentRoute: () => AppRoute,
} as any)
const AppGruposRoute = AppGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => AppRoute,
} as any)
const AppFaturasRoute = AppFaturasRouteImport.update({
  id: '/faturas',
  path: '/faturas',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresasRoute = AppEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasRoute = AppCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditoriaRoute = AppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppRoute,
} as any)
const AppAssinaturaRoute = AppAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertasRoute = AppAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendamentosRoute = AppAgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => AppRoute,
} as any)
const AdminSaasPlanosRoute = AdminSaasPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminSaasRoute,
} as any)
const AdminSaasPagamentosRoute = AdminSaasPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminSaasRoute,
} as any)
const AdminSaasLogsRoute = AdminSaasLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminSaasRoute,
} as any)
const AdminSaasLicencasRoute = AdminSaasLicencasRouteImport.update({
  id: '/licencas',
  path: '/licencas',
  getParentRoute: () => AdminSaasRoute,
} as any)
const AdminSaasDiagnosticoRoute = AdminSaasDiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => AdminSaasRoute,
} as any)
const AdminSaasClientesRoute = AdminSaasClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminSaasRoute,
} as any)
const AdminSaasAssinaturasRoute = AdminSaasAssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => AdminSaasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-saas': typeof AdminSaasRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/assinatura': typeof AssinaturaRoute
  '/assinaturas': typeof AssinaturasRoute
  '/checkout': typeof CheckoutRoute
  '/clientes': typeof ClientesRoute
  '/configurar': typeof ConfigurarRoute
  '/dashboard': typeof DashboardRoute
  '/faturas': typeof FaturasRoute
  '/licencas': typeof LicencasRoute
  '/login': typeof LoginRoute
  '/pagamentos': typeof PagamentosRoute
  '/pair': typeof PairRoute
  '/pareamento': typeof PareamentoRoute
  '/planos': typeof PlanosRoute
  '/player': typeof PlayerRouteWithChildren
  '/player-screen': typeof PlayerScreenRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin-saas/assinaturas': typeof AdminSaasAssinaturasRoute
  '/admin-saas/clientes': typeof AdminSaasClientesRoute
  '/admin-saas/diagnostico': typeof AdminSaasDiagnosticoRoute
  '/admin-saas/licencas': typeof AdminSaasLicencasRoute
  '/admin-saas/logs': typeof AdminSaasLogsRoute
  '/admin-saas/pagamentos': typeof AdminSaasPagamentosRoute
  '/admin-saas/planos': typeof AdminSaasPlanosRoute
  '/app/agendamentos': typeof AppAgendamentosRoute
  '/app/alertas': typeof AppAlertasRoute
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/empresas': typeof AppEmpresasRoute
  '/app/faturas': typeof AppFaturasRoute
  '/app/grupos': typeof AppGruposRoute
  '/app/midias': typeof AppMidiasRoute
  '/app/monitoramento': typeof AppMonitoramentoRoute
  '/app/operador': typeof AppOperadorRoute
  '/app/playlists': typeof AppPlaylistsRoute
  '/app/preview': typeof AppPreviewRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/telas': typeof AppTelasRoute
  '/app/unidades': typeof AppUnidadesRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/visualizacao': typeof AppVisualizacaoRoute
  '/display/$token': typeof DisplayTokenRoute
  '/player/$screenId': typeof PlayerScreenIdRoute
  '/player/web': typeof PlayerWebRoute
  '/admin-saas/': typeof AdminSaasIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assinatura': typeof AssinaturaRoute
  '/assinaturas': typeof AssinaturasRoute
  '/checkout': typeof CheckoutRoute
  '/clientes': typeof ClientesRoute
  '/configurar': typeof ConfigurarRoute
  '/dashboard': typeof DashboardRoute
  '/faturas': typeof FaturasRoute
  '/licencas': typeof LicencasRoute
  '/login': typeof LoginRoute
  '/pagamentos': typeof PagamentosRoute
  '/pair': typeof PairRoute
  '/pareamento': typeof PareamentoRoute
  '/planos': typeof PlanosRoute
  '/player': typeof PlayerRouteWithChildren
  '/player-screen': typeof PlayerScreenRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin-saas/assinaturas': typeof AdminSaasAssinaturasRoute
  '/admin-saas/clientes': typeof AdminSaasClientesRoute
  '/admin-saas/diagnostico': typeof AdminSaasDiagnosticoRoute
  '/admin-saas/licencas': typeof AdminSaasLicencasRoute
  '/admin-saas/logs': typeof AdminSaasLogsRoute
  '/admin-saas/pagamentos': typeof AdminSaasPagamentosRoute
  '/admin-saas/planos': typeof AdminSaasPlanosRoute
  '/app/agendamentos': typeof AppAgendamentosRoute
  '/app/alertas': typeof AppAlertasRoute
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/empresas': typeof AppEmpresasRoute
  '/app/faturas': typeof AppFaturasRoute
  '/app/grupos': typeof AppGruposRoute
  '/app/midias': typeof AppMidiasRoute
  '/app/monitoramento': typeof AppMonitoramentoRoute
  '/app/operador': typeof AppOperadorRoute
  '/app/playlists': typeof AppPlaylistsRoute
  '/app/preview': typeof AppPreviewRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/telas': typeof AppTelasRoute
  '/app/unidades': typeof AppUnidadesRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/visualizacao': typeof AppVisualizacaoRoute
  '/display/$token': typeof DisplayTokenRoute
  '/player/$screenId': typeof PlayerScreenIdRoute
  '/player/web': typeof PlayerWebRoute
  '/admin-saas': typeof AdminSaasIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-saas': typeof AdminSaasRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/assinatura': typeof AssinaturaRoute
  '/assinaturas': typeof AssinaturasRoute
  '/checkout': typeof CheckoutRoute
  '/clientes': typeof ClientesRoute
  '/configurar': typeof ConfigurarRoute
  '/dashboard': typeof DashboardRoute
  '/faturas': typeof FaturasRoute
  '/licencas': typeof LicencasRoute
  '/login': typeof LoginRoute
  '/pagamentos': typeof PagamentosRoute
  '/pair': typeof PairRoute
  '/pareamento': typeof PareamentoRoute
  '/planos': typeof PlanosRoute
  '/player': typeof PlayerRouteWithChildren
  '/player-screen': typeof PlayerScreenRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin-saas/assinaturas': typeof AdminSaasAssinaturasRoute
  '/admin-saas/clientes': typeof AdminSaasClientesRoute
  '/admin-saas/diagnostico': typeof AdminSaasDiagnosticoRoute
  '/admin-saas/licencas': typeof AdminSaasLicencasRoute
  '/admin-saas/logs': typeof AdminSaasLogsRoute
  '/admin-saas/pagamentos': typeof AdminSaasPagamentosRoute
  '/admin-saas/planos': typeof AdminSaasPlanosRoute
  '/app/agendamentos': typeof AppAgendamentosRoute
  '/app/alertas': typeof AppAlertasRoute
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/empresas': typeof AppEmpresasRoute
  '/app/faturas': typeof AppFaturasRoute
  '/app/grupos': typeof AppGruposRoute
  '/app/midias': typeof AppMidiasRoute
  '/app/monitoramento': typeof AppMonitoramentoRoute
  '/app/operador': typeof AppOperadorRoute
  '/app/playlists': typeof AppPlaylistsRoute
  '/app/preview': typeof AppPreviewRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/telas': typeof AppTelasRoute
  '/app/unidades': typeof AppUnidadesRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/visualizacao': typeof AppVisualizacaoRoute
  '/display/$token': typeof DisplayTokenRoute
  '/player/$screenId': typeof PlayerScreenIdRoute
  '/player/web': typeof PlayerWebRoute
  '/admin-saas/': typeof AdminSaasIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-saas'
    | '/app'
    | '/assinatura'
    | '/assinaturas'
    | '/checkout'
    | '/clientes'
    | '/configurar'
    | '/dashboard'
    | '/faturas'
    | '/licencas'
    | '/login'
    | '/pagamentos'
    | '/pair'
    | '/pareamento'
    | '/planos'
    | '/player'
    | '/player-screen'
    | '/recuperar-senha'
    | '/reset-password'
    | '/signup'
    | '/admin-saas/assinaturas'
    | '/admin-saas/clientes'
    | '/admin-saas/diagnostico'
    | '/admin-saas/licencas'
    | '/admin-saas/logs'
    | '/admin-saas/pagamentos'
    | '/admin-saas/planos'
    | '/app/agendamentos'
    | '/app/alertas'
    | '/app/assinatura'
    | '/app/auditoria'
    | '/app/campanhas'
    | '/app/configuracoes'
    | '/app/empresas'
    | '/app/faturas'
    | '/app/grupos'
    | '/app/midias'
    | '/app/monitoramento'
    | '/app/operador'
    | '/app/playlists'
    | '/app/preview'
    | '/app/relatorios'
    | '/app/telas'
    | '/app/unidades'
    | '/app/usuarios'
    | '/app/visualizacao'
    | '/display/$token'
    | '/player/$screenId'
    | '/player/web'
    | '/admin-saas/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assinatura'
    | '/assinaturas'
    | '/checkout'
    | '/clientes'
    | '/configurar'
    | '/dashboard'
    | '/faturas'
    | '/licencas'
    | '/login'
    | '/pagamentos'
    | '/pair'
    | '/pareamento'
    | '/planos'
    | '/player'
    | '/player-screen'
    | '/recuperar-senha'
    | '/reset-password'
    | '/signup'
    | '/admin-saas/assinaturas'
    | '/admin-saas/clientes'
    | '/admin-saas/diagnostico'
    | '/admin-saas/licencas'
    | '/admin-saas/logs'
    | '/admin-saas/pagamentos'
    | '/admin-saas/planos'
    | '/app/agendamentos'
    | '/app/alertas'
    | '/app/assinatura'
    | '/app/auditoria'
    | '/app/campanhas'
    | '/app/configuracoes'
    | '/app/empresas'
    | '/app/faturas'
    | '/app/grupos'
    | '/app/midias'
    | '/app/monitoramento'
    | '/app/operador'
    | '/app/playlists'
    | '/app/preview'
    | '/app/relatorios'
    | '/app/telas'
    | '/app/unidades'
    | '/app/usuarios'
    | '/app/visualizacao'
    | '/display/$token'
    | '/player/$screenId'
    | '/player/web'
    | '/admin-saas'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-saas'
    | '/app'
    | '/assinatura'
    | '/assinaturas'
    | '/checkout'
    | '/clientes'
    | '/configurar'
    | '/dashboard'
    | '/faturas'
    | '/licencas'
    | '/login'
    | '/pagamentos'
    | '/pair'
    | '/pareamento'
    | '/planos'
    | '/player'
    | '/player-screen'
    | '/recuperar-senha'
    | '/reset-password'
    | '/signup'
    | '/admin-saas/assinaturas'
    | '/admin-saas/clientes'
    | '/admin-saas/diagnostico'
    | '/admin-saas/licencas'
    | '/admin-saas/logs'
    | '/admin-saas/pagamentos'
    | '/admin-saas/planos'
    | '/app/agendamentos'
    | '/app/alertas'
    | '/app/assinatura'
    | '/app/auditoria'
    | '/app/campanhas'
    | '/app/configuracoes'
    | '/app/empresas'
    | '/app/faturas'
    | '/app/grupos'
    | '/app/midias'
    | '/app/monitoramento'
    | '/app/operador'
    | '/app/playlists'
    | '/app/preview'
    | '/app/relatorios'
    | '/app/telas'
    | '/app/unidades'
    | '/app/usuarios'
    | '/app/visualizacao'
    | '/display/$token'
    | '/player/$screenId'
    | '/player/web'
    | '/admin-saas/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminSaasRoute: typeof AdminSaasRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AssinaturaRoute: typeof AssinaturaRoute
  AssinaturasRoute: typeof AssinaturasRoute
  CheckoutRoute: typeof CheckoutRoute
  ClientesRoute: typeof ClientesRoute
  ConfigurarRoute: typeof ConfigurarRoute
  DashboardRoute: typeof DashboardRoute
  FaturasRoute: typeof FaturasRoute
  LicencasRoute: typeof LicencasRoute
  LoginRoute: typeof LoginRoute
  PagamentosRoute: typeof PagamentosRoute
  PairRoute: typeof PairRoute
  PareamentoRoute: typeof PareamentoRoute
  PlanosRoute: typeof PlanosRoute
  PlayerRoute: typeof PlayerRouteWithChildren
  PlayerScreenRoute: typeof PlayerScreenRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  DisplayTokenRoute: typeof DisplayTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player-screen': {
      id: '/player-screen'
      path: '/player-screen'
      fullPath: '/player-screen'
      preLoaderRoute: typeof PlayerScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pareamento': {
      id: '/pareamento'
      path: '/pareamento'
      fullPath: '/pareamento'
      preLoaderRoute: typeof PareamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos': {
      id: '/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof PagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licencas': {
      id: '/licencas'
      path: '/licencas'
      fullPath: '/licencas'
      preLoaderRoute: typeof LicencasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faturas': {
      id: '/faturas'
      path: '/faturas'
      fullPath: '/faturas'
      preLoaderRoute: typeof FaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurar': {
      id: '/configurar'
      path: '/configurar'
      fullPath: '/configurar'
      preLoaderRoute: typeof ConfigurarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinaturas': {
      id: '/assinaturas'
      path: '/assinaturas'
      fullPath: '/assinaturas'
      preLoaderRoute: typeof AssinaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-saas': {
      id: '/admin-saas'
      path: '/admin-saas'
      fullPath: '/admin-saas'
      preLoaderRoute: typeof AdminSaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin-saas/': {
      id: '/admin-saas/'
      path: '/'
      fullPath: '/admin-saas/'
      preLoaderRoute: typeof AdminSaasIndexRouteImport
      parentRoute: typeof AdminSaasRoute
    }
    '/player/web': {
      id: '/player/web'
      path: '/web'
      fullPath: '/player/web'
      preLoaderRoute: typeof PlayerWebRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/$screenId': {
      id: '/player/$screenId'
      path: '/$screenId'
      fullPath: '/player/$screenId'
      preLoaderRoute: typeof PlayerScreenIdRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/display/$token': {
      id: '/display/$token'
      path: '/display/$token'
      fullPath: '/display/$token'
      preLoaderRoute: typeof DisplayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/visualizacao': {
      id: '/app/visualizacao'
      path: '/visualizacao'
      fullPath: '/app/visualizacao'
      preLoaderRoute: typeof AppVisualizacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usuarios': {
      id: '/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/unidades': {
      id: '/app/unidades'
      path: '/unidades'
      fullPath: '/app/unidades'
      preLoaderRoute: typeof AppUnidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/telas': {
      id: '/app/telas'
      path: '/telas'
      fullPath: '/app/telas'
      preLoaderRoute: typeof AppTelasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/preview': {
      id: '/app/preview'
      path: '/preview'
      fullPath: '/app/preview'
      preLoaderRoute: typeof AppPreviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/playlists': {
      id: '/app/playlists'
      path: '/playlists'
      fullPath: '/app/playlists'
      preLoaderRoute: typeof AppPlaylistsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/operador': {
      id: '/app/operador'
      path: '/operador'
      fullPath: '/app/operador'
      preLoaderRoute: typeof AppOperadorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/monitoramento': {
      id: '/app/monitoramento'
      path: '/monitoramento'
      fullPath: '/app/monitoramento'
      preLoaderRoute: typeof AppMonitoramentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/midias': {
      id: '/app/midias'
      path: '/midias'
      fullPath: '/app/midias'
      preLoaderRoute: typeof AppMidiasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grupos': {
      id: '/app/grupos'
      path: '/grupos'
      fullPath: '/app/grupos'
      preLoaderRoute: typeof AppGruposRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/faturas': {
      id: '/app/faturas'
      path: '/faturas'
      fullPath: '/app/faturas'
      preLoaderRoute: typeof AppFaturasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/empresas': {
      id: '/app/empresas'
      path: '/empresas'
      fullPath: '/app/empresas'
      preLoaderRoute: typeof AppEmpresasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campanhas': {
      id: '/app/campanhas'
      path: '/campanhas'
      fullPath: '/app/campanhas'
      preLoaderRoute: typeof AppCampanhasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/auditoria': {
      id: '/app/auditoria'
      path: '/auditoria'
      fullPath: '/app/auditoria'
      preLoaderRoute: typeof AppAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assinatura': {
      id: '/app/assinatura'
      path: '/assinatura'
      fullPath: '/app/assinatura'
      preLoaderRoute: typeof AppAssinaturaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alertas': {
      id: '/app/alertas'
      path: '/alertas'
      fullPath: '/app/alertas'
      preLoaderRoute: typeof AppAlertasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agendamentos': {
      id: '/app/agendamentos'
      path: '/agendamentos'
      fullPath: '/app/agendamentos'
      preLoaderRoute: typeof AppAgendamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin-saas/planos': {
      id: '/admin-saas/planos'
      path: '/planos'
      fullPath: '/admin-saas/planos'
      preLoaderRoute: typeof AdminSaasPlanosRouteImport
      parentRoute: typeof AdminSaasRoute
    }
    '/admin-saas/pagamentos': {
      id: '/admin-saas/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin-saas/pagamentos'
      preLoaderRoute: typeof AdminSaasPagamentosRouteImport
      parentRoute: typeof AdminSaasRoute
    }
    '/admin-saas/logs': {
      id: '/admin-saas/logs'
      path: '/logs'
      fullPath: '/admin-saas/logs'
      preLoaderRoute: typeof AdminSaasLogsRouteImport
      parentRoute: typeof AdminSaasRoute
    }
    '/admin-saas/licencas': {
      id: '/admin-saas/licencas'
      path: '/licencas'
      fullPath: '/admin-saas/licencas'
      preLoaderRoute: typeof AdminSaasLicencasRouteImport
      parentRoute: typeof AdminSaasRoute
    }
    '/admin-saas/diagnostico': {
      id: '/admin-saas/diagnostico'
      path: '/diagnostico'
      fullPath: '/admin-saas/diagnostico'
      preLoaderRoute: typeof AdminSaasDiagnosticoRouteImport
      parentRoute: typeof AdminSaasRoute
    }
    '/admin-saas/clientes': {
      id: '/admin-saas/clientes'
      path: '/clientes'
      fullPath: '/admin-saas/clientes'
      preLoaderRoute: typeof AdminSaasClientesRouteImport
      parentRoute: typeof AdminSaasRoute
    }
    '/admin-saas/assinaturas': {
      id: '/admin-saas/assinaturas'
      path: '/assinaturas'
      fullPath: '/admin-saas/assinaturas'
      preLoaderRoute: typeof AdminSaasAssinaturasRouteImport
      parentRoute: typeof AdminSaasRoute
    }
  }
}

interface AdminSaasRouteChildren {
  AdminSaasAssinaturasRoute: typeof AdminSaasAssinaturasRoute
  AdminSaasClientesRoute: typeof AdminSaasClientesRoute
  AdminSaasDiagnosticoRoute: typeof AdminSaasDiagnosticoRoute
  AdminSaasLicencasRoute: typeof AdminSaasLicencasRoute
  AdminSaasLogsRoute: typeof AdminSaasLogsRoute
  AdminSaasPagamentosRoute: typeof AdminSaasPagamentosRoute
  AdminSaasPlanosRoute: typeof AdminSaasPlanosRoute
  AdminSaasIndexRoute: typeof AdminSaasIndexRoute
}

const AdminSaasRouteChildren: AdminSaasRouteChildren = {
  AdminSaasAssinaturasRoute: AdminSaasAssinaturasRoute,
  AdminSaasClientesRoute: AdminSaasClientesRoute,
  AdminSaasDiagnosticoRoute: AdminSaasDiagnosticoRoute,
  AdminSaasLicencasRoute: AdminSaasLicencasRoute,
  AdminSaasLogsRoute: AdminSaasLogsRoute,
  AdminSaasPagamentosRoute: AdminSaasPagamentosRoute,
  AdminSaasPlanosRoute: AdminSaasPlanosRoute,
  AdminSaasIndexRoute: AdminSaasIndexRoute,
}

const AdminSaasRouteWithChildren = AdminSaasRoute._addFileChildren(
  AdminSaasRouteChildren,
)

interface AppRouteChildren {
  AppAgendamentosRoute: typeof AppAgendamentosRoute
  AppAlertasRoute: typeof AppAlertasRoute
  AppAssinaturaRoute: typeof AppAssinaturaRoute
  AppAuditoriaRoute: typeof AppAuditoriaRoute
  AppCampanhasRoute: typeof AppCampanhasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppEmpresasRoute: typeof AppEmpresasRoute
  AppFaturasRoute: typeof AppFaturasRoute
  AppGruposRoute: typeof AppGruposRoute
  AppMidiasRoute: typeof AppMidiasRoute
  AppMonitoramentoRoute: typeof AppMonitoramentoRoute
  AppOperadorRoute: typeof AppOperadorRoute
  AppPlaylistsRoute: typeof AppPlaylistsRoute
  AppPreviewRoute: typeof AppPreviewRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppTelasRoute: typeof AppTelasRoute
  AppUnidadesRoute: typeof AppUnidadesRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppVisualizacaoRoute: typeof AppVisualizacaoRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendamentosRoute: AppAgendamentosRoute,
  AppAlertasRoute: AppAlertasRoute,
  AppAssinaturaRoute: AppAssinaturaRoute,
  AppAuditoriaRoute: AppAuditoriaRoute,
  AppCampanhasRoute: AppCampanhasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppEmpresasRoute: AppEmpresasRoute,
  AppFaturasRoute: AppFaturasRoute,
  AppGruposRoute: AppGruposRoute,
  AppMidiasRoute: AppMidiasRoute,
  AppMonitoramentoRoute: AppMonitoramentoRoute,
  AppOperadorRoute: AppOperadorRoute,
  AppPlaylistsRoute: AppPlaylistsRoute,
  AppPreviewRoute: AppPreviewRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppTelasRoute: AppTelasRoute,
  AppUnidadesRoute: AppUnidadesRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppVisualizacaoRoute: AppVisualizacaoRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PlayerRouteChildren {
  PlayerScreenIdRoute: typeof PlayerScreenIdRoute
  PlayerWebRoute: typeof PlayerWebRoute
}

const PlayerRouteChildren: PlayerRouteChildren = {
  PlayerScreenIdRoute: PlayerScreenIdRoute,
  PlayerWebRoute: PlayerWebRoute,
}

const PlayerRouteWithChildren =
  PlayerRoute._addFileChildren(PlayerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminSaasRoute: AdminSaasRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AssinaturaRoute: AssinaturaRoute,
  AssinaturasRoute: AssinaturasRoute,
  CheckoutRoute: CheckoutRoute,
  ClientesRoute: ClientesRoute,
  ConfigurarRoute: ConfigurarRoute,
  DashboardRoute: DashboardRoute,
  FaturasRoute: FaturasRoute,
  LicencasRoute: LicencasRoute,
  LoginRoute: LoginRoute,
  PagamentosRoute: PagamentosRoute,
  PairRoute: PairRoute,
  PareamentoRoute: PareamentoRoute,
  PlanosRoute: PlanosRoute,
  PlayerRoute: PlayerRouteWithChildren,
  PlayerScreenRoute: PlayerScreenRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  DisplayTokenRoute: DisplayTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
